//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gra_SportScheduleSchedules
    {
        public int ModuleID { get; set; }
        public int ScheduleId { get; set; }
        public Nullable<int> ScheduleType { get; set; }
        public Nullable<int> EditMode { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string Rules { get; set; }
    }
}
