//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gra_SportScheduleGameTypes
    {
        public int ModuleID { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string GameType { get; set; }
        public string GameValue { get; set; }
        public int CreatedByUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ShowHome { get; set; }
        public Nullable<int> ViewOrder { get; set; }
        public Nullable<int> Elimination { get; set; }
    }
}
