//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gra_SportScheduleEventTeams
    {
        public int ModuleID { get; set; }
        public int PoolTeamId { get; set; }
        public Nullable<int> PoolId { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<int> Ties { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> RunsFor { get; set; }
        public Nullable<int> RunsAgainst { get; set; }
        public Nullable<int> Per { get; set; }
        public string GamesBack { get; set; }
        public string TeamNote { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedByUser { get; set; }
        public Nullable<int> ViewOrder { get; set; }
    }
}
