//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gra_SportScheduleScheduleAddOns
    {
        public int ItemId { get; set; }
        public int ModuleID { get; set; }
        public Nullable<int> EventId { get; set; }
        public string ScheduleText { get; set; }
        public Nullable<int> ViewOrder { get; set; }
        public Nullable<int> CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
