//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gra_SportScheduleTeams
    {
        public int ModuleID { get; set; }
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> ViewOrder { get; set; }
        public int CreatedByUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
