//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gra_SportSchedule> gra_SportSchedule { get; set; }
        public virtual DbSet<gra_SportScheduleEventTeams> gra_SportScheduleEventTeams { get; set; }
        public virtual DbSet<gra_SportScheduleGames> gra_SportScheduleGames { get; set; }
        public virtual DbSet<gra_SportScheduleGameTypes> gra_SportScheduleGameTypes { get; set; }
        public virtual DbSet<gra_SportScheduleLocations> gra_SportScheduleLocations { get; set; }
        public virtual DbSet<gra_SportSchedulePools> gra_SportSchedulePools { get; set; }
        public virtual DbSet<gra_SportScheduleScheduleAddOns> gra_SportScheduleScheduleAddOns { get; set; }
        public virtual DbSet<gra_SportScheduleSchedules> gra_SportScheduleSchedules { get; set; }
        public virtual DbSet<gra_SportScheduleTeams> gra_SportScheduleTeams { get; set; }
        public virtual DbSet<sportScheduleFE> sportScheduleFEs { get; set; }
    }
}
